export const ROUTES = {
    HOME: "/",
    DASHBOARD: "/dashboard",
    PROJECTS: "/projects",
    TASKS: "/tasks",
    MY_TASKS: "/my-tasks",
    PROFILE: "/profile",
    SETTINGS: "/settings",
    NOTIFICATIONS: "/notifications",
    HELP: "/help-support",
    LOGIN: "/login",
} as const

export const API_ROUTES = {
    AUTH: {
        LOGIN: "/auth/login",
        REGISTER: "/auth/register",
        LOGOUT: "/auth/logout",
        REFRESH: "/auth/refresh",
    },
    PROJECTS: {
        LIST: "/projects",
        CREATE: "/projects",
        SEARCH: "/projects/search",
        DETAIL: (id: string) => `/projects/${id}`,
        UPDATE: (id: string) => `/projects/${id}`,
        DELETE: (id: string) => `/projects/${id}`,
        TASKS: (projectId: string) => `/projects/${projectId}/tasks`,
        MEMBERS: {
            ADD: (projectId: string) => `/projects/${projectId}/members`,
            REMOVE: (projectId: string, memberId: string) => `/projects/${projectId}/members/${memberId}`,
        },
    },
    TASKS: {
        LIST: "/users/me/tasks",
        ALL: "/tasks",
        CREATE: "/tasks",
        DETAIL: (id: string) => `/tasks/${id}`,
        UPDATE: (id: string) => `/tasks/${id}`,
        DELETE: (id: string) => `/tasks/${id}`,
        STATUS: (id: string) => `/tasks/${id}/status`,
        ARCHIVE: (id: string) => `/tasks/${id}/archive`,
        RESTORE: (id: string) => `/tasks/${id}/restore`,
        LABELS: (taskId: string) => `/tasks/${taskId}/labels`,
        SUBTASKS: (taskId: string) => `/tasks/${taskId}/subtasks`,
        ASSIGNEES: (taskId: string) => `/tasks/${taskId}/assignees`,
        PROJECT_MEMBERS: (taskId: string) => `/tasks/${taskId}/project-members`,
    },
    USERS: {
        LIST: "/users",
        PROFILE: "/users/profile",
        UPDATE: "/users/profile",
        AVATAR: "/users/avatar",
        AVATAR_OF: (userId: string) => `/users/avatar/${userId}`,
        DETAIL: (id: string) => `/users/${id}`,
    },
} as const
