version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: smart-task-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smart_task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smart-task-network

networks:
  smart-task-network:
    driver: bridge

volumes:
  postgres_data:
